### ISSUE TITLE
Request id is hardcoded in the http(s) client

### ISSUE THREAD

**Issue by nkmanolovsumup** [fanduel/jsonrpc2-elixir#12] opened 2018-07-26 15:18 UTC
When making a call via the http client no custom request id can be specified. The id is hardcoded to 0.

https://github.com/fanduel/jsonrpc2-elixir/blob/master/lib/jsonrpc2/clients/http.ex#L20

**Comment by ericentin** [comment] 2018-07-26 15:33
I'm not sure I understand what issue this is causing? AFAIK the purpose of the request id is when you are multiplexing multiple requests over a single connection, in order to identify which request a response corresponds to.

**Comment by nkmanolovsumup** [comment] 2018-07-26 16:02
Yes, the ID is used for multiplexing (and primarily so), however, it's purpose is not defined in the [specification](https://www.jsonrpc.org/specification#request_object) as such. I agree that for single http calls it doesn't make too much sense, however, the library assumes that the client doesn't need to pass a custom id. It would be nice to be able optionally pass it.

**Comment by ericentin** [comment] 2018-07-26 16:12
The purpose is defined in the spec, as far as I can tell:

```
The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.
```

If you want to add a PR to add an optional argument to change the request ID from 0 to another value, I would welcome it, but it will also have to validate that the passed value is a valid request ID.

**Comment by whitered** [comment] 2018-09-10 20:15
+1 here. I'm experiencing issues with hardcoded id too, the problem is tendermint rpc server doesn't accept integer id value (yes, it's Tendermint's fault but still my problem). I'm going to change the default id to "0" (string), any chance this change can be merged in the lib?

**Comment by ericentin** [comment] 2019-05-28 17:08
Resolved, released soon

**Closed by ericentin** 2019-05-28 17:08 UTC
